# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Печеньки",
  "description": "Подходят для удобрения людей"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "адрес не дом и не улица, мой адрес Советский Союз",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/3/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 2,
      "price": 1.80
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json
